
---
spring:
  config:
    activate:
      on-profile: local
mqtt:
  url: tcp://10.28.3.180:1883
  username: "ENC(NYOhdVxUIopB5z/+HSpxUIQQr2OV5YMM)"
  password: "ENC(NYOhdVxUIopB5z/+HSpxUIQQr2OV5YMM)"
---
spring:
  config:
    activate:
      on-profile: dev
mqtt:
  url: tcp://10.0.1.114:1883
  username: "ENC(X9Ya7F/TCdkvH7MjV6z0fg==)"
  password: "ENC(AL89eBhofqiKifz+o7M1FJyXK7Bv0fTn)"