pluginManagement {
    plugins {
        id 'org.jetbrains.kotlin.jvm' version '1.9.23'
    }
}
plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '0.5.0'
}

rootProject.name = 'tms'

include 'tms-core'
project(':tms-core').projectDir = file('tms-library/tms-core')

include 'lib-redis'
project(':lib-redis').projectDir = file('tms-library/lib-redis')

include 'lib-mqtt'
project(':lib-mqtt').projectDir = file('tms-library/lib-mqtt')

include 'tms-admin'
project(':tms-admin').projectDir = file('tms-admin')

include 'tms-api'
project(':tms-api').projectDir = file('tms-api')