### 로그인
< {%
    client.global.clearAll()

    client.global.set("test_groupCode", "AdminStatus");
%}
POST {{admin}}/login
Content-Type: application/json

{
  "email": "admin@obigo.com",
  "password": "1234"
}
> {%
    client.global.set("access-token", response.body.data.accessToken);
    client.global.set("refresh-token", response.body.data.refreshToken);
%}




### 유효한 공통코드 가져오기
GET {{admin}}/common-code/valid-common-codes/AdminStatus
Content-Type: application/json
Authorization: Bearer {{access-token}}



### 공통코드그룹 목록 조회
GET {{admin}}/common-code/common-code-groups
Content-Type: application/json
Authorization: Bearer {{access-token}}


### 공통코드그룹 목록 조회 (검색어 있음)
GET {{admin}}/common-code/common-code-groups?comCodeGroupCd=&comCodeGroupName=
Content-Type: application/json
Authorization: Bearer {{access-token}}



### 공통코드그룹 생성처리
POST {{admin}}/common-code/common-code-group
Content-Type: application/json
Authorization: Bearer {{access-token}}

{
  "comCodeGroupCd": "TestGroup",
  "comCodeGroupName": "테스트그룹"
}

### 공통코드그룹 수정처리
PUT {{admin}}/common-code/common-code-group
Content-Type: application/json
Authorization: Bearer {{access-token}}

{
  "comCodeGroupCd": "TestGroup",
  "comCodeGroupName": "테스트 그룹1"
}




### 공통코드 목록 조회
GET {{admin}}/common-code/common-codes/TestGroup
Content-Type: application/json
Authorization: Bearer {{access-token}}


### 공통코드 생성처리
POST {{admin}}/common-code/common-code
Content-Type: application/json
Authorization: Bearer {{access-token}}

{
  "comCodeGroupCd": "TestGroup",
  "comCodeCd": "TestCode",
  "comCodeName": "테스트코드",
  "sortOrder": 1,
  "usageYn": "Y",
  "attribute1": "속성1",
  "attribute2": "속성2",
  "attribute3": "속성3"

}



### 공통코드 삭제
DELETE {{admin}}/common-code/common-code
Content-Type: application/json
Authorization: Bearer {{access-token}}

{
  "comCodeSeqs": [17]
}



### 공통코드그룹 삭제 : 하위공통코드 남은 상태이므로 삭제되면 안됨
DELETE {{admin}}/common-code/common-code-group
Content-Type: application/json
Authorization: Bearer {{access-token}}

{
  "comCodeGroupCds": ["TestGroup"]
}