### 로그인 : API
POST {{api}}/auth/login
Content-Type: application/json

{
  "loginId": "driver03",
  "password": "1234"
}
> {%
    client.global.set("access-token", response.body.data.accessToken);
    client.global.set("refresh-token", response.body.data.refreshToken);
%}


### 월별 통계
GET {{api}}/statistics/monthly?yyyyMM=202410
Content-Type: application/json
Authorization: Bearer {{access-token}}


