server {
    #server_name  localhost;
    server_name evcar-tms.obigo.com;
    #access_log  /var/log/nginx/access.log  main;

     location /tms-web/admin  {
        alias /app/service/administrator/dist;
    }

     location /tms-web/mobile  {
        alias /app/service/mobile/dist;
    }

     location /tms-web/app  {
        alias /app/service/app/dist;
    }



    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
               root   /usr/share/nginx/html;
    }


    location ^~ /tms/admin {
        proxy_pass http://10.0.1.155:8090;
    }


    ## SSE 를 위한 설정(2024.10.31 hannah)
    location ^~ /tms/api/delivery/subscribe {
        proxy_set_header Connection '';
        proxy_set_header Cache-Control 'no-cache';
        proxy_set_header X-Accel-Buffering 'no';
        proxy_set_header Content-Type 'text/event-stream';
        proxy_buffering off;
        chunked_transfer_encoding on;
        proxy_read_timeout 86400s;

        proxy_pass http://10.0.1.155:8091;


    }

    location ^~ /tms/api {
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Host $server_name;

        proxy_pass http://10.0.1.155:8091;
    }



    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/evcar-tms.obigo.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/evcar-tms.obigo.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}
server {
    if ($host = evcar-tms.obigo.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    server_name evcar-tms.obigo.com;
    listen 80;
    return 404; # managed by Certbot


}