INSERT INTO public.t_center
(center_name, center_type_cd, center_addr_1, center_addr_2, zip_code, latitude, longitude, total_area, manager_name, contact_num, usage_yn, created_at, creator_seq, modified_at, modifier_seq)
VALUES('판교 롯데마트', 'SUPERMARKET', '경기 성남시 분당구 대왕판교로606번길', '58', '13525', 37.3955577, 127.1133755, 1000.352, '김오비고1', '010-1234-5678', 'Y', '2024-07-25 12:05:13.543', 1, '2024-07-25 14:03:46.539', 1);
INSERT INTO public.t_center
(center_name, center_type_cd, center_addr_1, center_addr_2, zip_code, latitude, longitude, total_area, manager_name, contact_num, usage_yn, created_at, creator_seq, modified_at, modifier_seq)
VALUES('롯데택배 판교동원대리점', 'DELIVERY', '경기도 광주시 경충대로 2056', '롯데택배 판교동원대리점', '13465', 37.4060975, 127.2145405, 177.5, '김롯데', '031-752-4786', 'Y', '2024-07-25 14:15:59.800', 1, '2024-07-25 14:15:59.801', 1);


INSERT INTO public.t_driver (driver_name, center_seq, login_id, ext_system_linked_id, "password", driver_phone_num, email, driver_license_num, driver_license_date, driver_license_agency, working_days, working_start_hour, working_end_hour, status_cd, comp_name, created_at, creator_seq, modified_at, modifier_seq) VALUES
    ('홍길동',  (SELECT center_seq FROM t_center WHERE center_name='롯데택배 판교동원대리점')
    ,'driver01', 'lotte_driver01', '$2a$10$jdX4n.Jr7464BDaiZAdv4O8vuvCF20zmuXj.H4Osts2QLwrOK2QU6', '010-1234-5678', 'test@obigo.com', '11-02-33333', '2023-01-01', '운전면허 발급기관', '월화수목금', '09:00:00', '18:00:00', 'WORKING', '오비고', '2024-07-23 17:50:44.384', 1, '2024-07-23 17:50:44.384', 1);

INSERT INTO public.t_driver (driver_name, center_seq, login_id, ext_system_linked_id, "password", driver_phone_num, email, driver_license_num, driver_license_date, driver_license_agency, working_days, working_start_hour, working_end_hour, status_cd, comp_name, created_at, creator_seq, modified_at, modifier_seq) VALUES
    ('김기사',  (SELECT center_seq FROM t_center WHERE center_name='판교 롯데마트')
    , 'driver02', 'lotte_driver02', '$2a$10$jdX4n.Jr7464BDaiZAdv4O8vuvCF20zmuXj.H4Osts2QLwrOK2QU6', '010-1234-5678', 'test@obigo.com', '11-02-33333', '2023-01-01', '운전면허 발급기관', '월화수목금', '09:00:00', '18:00:00', 'WORKING', '오비고', '2024-07-29 16:02:17.326', 1, '2024-07-29 16:02:17.326', 1);



-- 샘플 권역 20개 + 범위
INSERT INTO public.t_region (region_name, created_at, creator_seq, modified_at, modifier_seq) VALUES ('분당 판교동권역', NOW(), 1, NOW(), 1);
INSERT INTO public.t_region_range (region_seq, eup_myeon_dong) VALUES ((SELECT region_seq FROM t_region WHERE region_name='분당 판교동권역'), '판교동');
INSERT INTO public.t_region (region_name, created_at, creator_seq, modified_at, modifier_seq) VALUES ('분당 삼평동권역', NOW(), 1, NOW(), 1);
INSERT INTO public.t_region_range (region_seq, eup_myeon_dong) VALUES ((SELECT region_seq FROM t_region WHERE region_name='분당 삼평동권역'), '삼평동');
INSERT INTO public.t_region (region_name, created_at, creator_seq, modified_at, modifier_seq) VALUES ('분당 백현동권역', NOW(), 1, NOW(), 1);
INSERT INTO public.t_region_range (region_seq, eup_myeon_dong) VALUES ((SELECT region_seq FROM t_region WHERE region_name='분당 백현동권역'), '백현동');
INSERT INTO public.t_region (region_name, created_at, creator_seq, modified_at, modifier_seq) VALUES ('분당 운중동권역', NOW(), 1, NOW(), 1);
INSERT INTO public.t_region_range (region_seq, eup_myeon_dong) VALUES ((SELECT region_seq FROM t_region WHERE region_name='분당 운중동권역'), '운중동');
INSERT INTO public.t_region (region_name, created_at, creator_seq, modified_at, modifier_seq) VALUES ('분당 서현동권역', NOW(), 1, NOW(), 1);
INSERT INTO public.t_region_range (region_seq, eup_myeon_dong) VALUES ((SELECT region_seq FROM t_region WHERE region_name='분당 서현동권역'), '서현동');
INSERT INTO public.t_region (region_name, created_at, creator_seq, modified_at, modifier_seq) VALUES ('분당 수내동권역', NOW(), 1, NOW(), 1);
INSERT INTO public.t_region_range (region_seq, eup_myeon_dong) VALUES ((SELECT region_seq FROM t_region WHERE region_name='분당 수내동권역'), '수내동');
INSERT INTO public.t_region (region_name, created_at, creator_seq, modified_at, modifier_seq) VALUES ('분당 정자동권역', NOW(), 1, NOW(), 1);
INSERT INTO public.t_region_range (region_seq, eup_myeon_dong) VALUES ((SELECT region_seq FROM t_region WHERE region_name='분당 정자동권역'), '정자동');
INSERT INTO public.t_region (region_name, created_at, creator_seq, modified_at, modifier_seq) VALUES ('분당 분당동권역', NOW(), 1, NOW(), 1);
INSERT INTO public.t_region_range (region_seq, eup_myeon_dong) VALUES ((SELECT region_seq FROM t_region WHERE region_name='분당 분당동권역'), '분당동');
INSERT INTO public.t_region (region_name, created_at, creator_seq, modified_at, modifier_seq) VALUES ('분당 야탑동권역', NOW(), 1, NOW(), 1);
INSERT INTO public.t_region_range (region_seq, eup_myeon_dong) VALUES ((SELECT region_seq FROM t_region WHERE region_name='분당 야탑동권역'), '야탑동');
INSERT INTO public.t_region (region_name, created_at, creator_seq, modified_at, modifier_seq) VALUES ('분당 이매동권역', NOW(), 1, NOW(), 1);
INSERT INTO public.t_region_range (region_seq, eup_myeon_dong) VALUES ((SELECT region_seq FROM t_region WHERE region_name='분당 이매동권역'), '이매동');
INSERT INTO public.t_region (region_name, created_at, creator_seq, modified_at, modifier_seq) VALUES ('분당 매송동권역', NOW(), 1, NOW(), 1);
INSERT INTO public.t_region_range (region_seq, eup_myeon_dong) VALUES ((SELECT region_seq FROM t_region WHERE region_name='분당 매송동권역'), '매송동');
INSERT INTO public.t_region (region_name, created_at, creator_seq, modified_at, modifier_seq) VALUES ('분당 구미동권역', NOW(), 1, NOW(), 1);
INSERT INTO public.t_region_range (region_seq, eup_myeon_dong) VALUES ((SELECT region_seq FROM t_region WHERE region_name='분당 구미동권역'), '구미동');
INSERT INTO public.t_region (region_name, created_at, creator_seq, modified_at, modifier_seq) VALUES ('분당 금곡동권역', NOW(), 1, NOW(), 1);
INSERT INTO public.t_region_range (region_seq, eup_myeon_dong) VALUES ((SELECT region_seq FROM t_region WHERE region_name='분당 금곡동권역'), '금곡동');
INSERT INTO public.t_region (region_name, created_at, creator_seq, modified_at, modifier_seq) VALUES ('분당 대장동권역', NOW(), 1, NOW(), 1);
INSERT INTO public.t_region_range (region_seq, eup_myeon_dong) VALUES ((SELECT region_seq FROM t_region WHERE region_name='분당 대장동권역'), '대장동');
INSERT INTO public.t_region (region_name, created_at, creator_seq, modified_at, modifier_seq) VALUES ('분당 석운동권역', NOW(), 1, NOW(), 1);
INSERT INTO public.t_region_range (region_seq, eup_myeon_dong) VALUES ((SELECT region_seq FROM t_region WHERE region_name='분당 석운동권역'), '석운동');
INSERT INTO public.t_region (region_name, created_at, creator_seq, modified_at, modifier_seq) VALUES ('분당 하산운동권역', NOW(), 1, NOW(), 1);
INSERT INTO public.t_region_range (region_seq, eup_myeon_dong) VALUES ((SELECT region_seq FROM t_region WHERE region_name='분당 하산운동권역'), '하산운동');
INSERT INTO public.t_region (region_name, created_at, creator_seq, modified_at, modifier_seq) VALUES ('분당 율동권역', NOW(), 1, NOW(), 1);
INSERT INTO public.t_region_range (region_seq, eup_myeon_dong) VALUES ((SELECT region_seq FROM t_region WHERE region_name='분당 율동권역'), '율동');
INSERT INTO public.t_region (region_name, created_at, creator_seq, modified_at, modifier_seq) VALUES ('분당 궁내동권역', NOW(), 1, NOW(), 1);
INSERT INTO public.t_region_range (region_seq, eup_myeon_dong) VALUES ((SELECT region_seq FROM t_region WHERE region_name='분당 궁내동권역'), '궁내동');
INSERT INTO public.t_region (region_name, created_at, creator_seq, modified_at, modifier_seq) VALUES ('분당 동원동권역', NOW(), 1, NOW(), 1);
INSERT INTO public.t_region_range (region_seq, eup_myeon_dong) VALUES ((SELECT region_seq FROM t_region WHERE region_name='분당 동원동권역'), '동원동');
INSERT INTO public.t_region (region_name, created_at, creator_seq, modified_at, modifier_seq) VALUES ('분당 여수동권역', NOW(), 1, NOW(), 1);
INSERT INTO public.t_region_range (region_seq, eup_myeon_dong) VALUES ((SELECT region_seq FROM t_region WHERE region_name='분당 여수동권역'), '여수동');

-- 샘플 차량 20대
INSERT INTO public.t_vehicle (center_seq, driver_seq, region_seq, vehicle_name, model, vehicle_type_cd, vehicle_num, vehicle_reg_num, model_year, vehicle_reg_area, owner_name, length, width, ton_grade, max_loading_capacity, fuel_type_cd, fuel_efficiency, vehicle_use_type_cd, garage_name, usage_yn, created_at, creator_seq, modified_at, modifier_seq) VALUES ((SELECT center_seq FROM t_center WHERE center_name='판교 롯데마트'), (SELECT driver_seq FROM t_driver WHERE login_id='driver01'), (SELECT region_seq FROM t_region WHERE region_name='분당 판교동권역'), '판교 01호차', '마이티', 'CARGO', '12가 3401', '서울13바3401', '2021', '경기', '김오비고', '5.2m', '2.1m', '1톤', '1000kg', 'LPG', '8.5km/L', 'RENTED', '판교차고지', 'Y', NOW(), 1, NOW(), 1);
INSERT INTO public.t_vehicle (center_seq, driver_seq, region_seq, vehicle_name, model, vehicle_type_cd, vehicle_num, vehicle_reg_num, model_year, vehicle_reg_area, owner_name, length, width, ton_grade, max_loading_capacity, fuel_type_cd, fuel_efficiency, vehicle_use_type_cd, garage_name, usage_yn, created_at, creator_seq, modified_at, modifier_seq) VALUES ((SELECT center_seq FROM t_center WHERE center_name='롯데택배 판교동원대리점'), (SELECT driver_seq FROM t_driver WHERE login_id='driver02'), (SELECT region_seq FROM t_region WHERE region_name='분당 삼평동권역'), '판교 02호차', '마이티', 'BOX_TRUCK', '12가 3402', '서울14바3402', '2022', '경기', '김오비고', '5.2m', '2.1m', '1톤', '1000kg', 'GASOLINE', '8.5km/L', 'OWN', '판교차고지', 'Y', NOW(), 1, NOW(), 1);
INSERT INTO public.t_vehicle (center_seq, driver_seq, region_seq, vehicle_name, model, vehicle_type_cd, vehicle_num, vehicle_reg_num, model_year, vehicle_reg_area, owner_name, length, width, ton_grade, max_loading_capacity, fuel_type_cd, fuel_efficiency, vehicle_use_type_cd, garage_name, usage_yn, created_at, creator_seq, modified_at, modifier_seq) VALUES ((SELECT center_seq FROM t_center WHERE center_name='판교 롯데마트'), NULL, (SELECT region_seq FROM t_region WHERE region_name='분당 백현동권역'), '판교 03호차', '마이티', 'WING_BODY', '12가 3403', '서울15바3403', '2023', '경기', '김오비고', '5.2m', '2.1m', '1톤', '1000kg', 'DIESEL', '8.5km/L', 'RENTED', '판교차고지', 'Y', NOW(), 1, NOW(), 1);
INSERT INTO public.t_vehicle (center_seq, driver_seq, region_seq, vehicle_name, model, vehicle_type_cd, vehicle_num, vehicle_reg_num, model_year, vehicle_reg_area, owner_name, length, width, ton_grade, max_loading_capacity, fuel_type_cd, fuel_efficiency, vehicle_use_type_cd, garage_name, usage_yn, created_at, creator_seq, modified_at, modifier_seq) VALUES ((SELECT center_seq FROM t_center WHERE center_name='롯데택배 판교동원대리점'), NULL, (SELECT region_seq FROM t_region WHERE region_name='분당 운중동권역'), '판교 04호차', '마이티', 'CARGO', '12가 3404', '서울16바3404', '2020', '경기', '김오비고', '5.2m', '2.1m', '1톤', '1000kg', 'ELECTRIC', '8.5km/L', 'OWN', '판교차고지', 'Y', NOW(), 1, NOW(), 1);
INSERT INTO public.t_vehicle (center_seq, driver_seq, region_seq, vehicle_name, model, vehicle_type_cd, vehicle_num, vehicle_reg_num, model_year, vehicle_reg_area, owner_name, length, width, ton_grade, max_loading_capacity, fuel_type_cd, fuel_efficiency, vehicle_use_type_cd, garage_name, usage_yn, created_at, creator_seq, modified_at, modifier_seq) VALUES ((SELECT center_seq FROM t_center WHERE center_name='판교 롯데마트'), NULL, (SELECT region_seq FROM t_region WHERE region_name='분당 서현동권역'), '판교 05호차', '마이티', 'BOX_TRUCK', '12가 3405', '서울17바3405', '2021', '경기', '김오비고', '5.2m', '2.1m', '1톤', '1000kg', 'LPG', '8.5km/L', 'RENTED', '판교차고지', 'Y', NOW(), 1, NOW(), 1);
INSERT INTO public.t_vehicle (center_seq, driver_seq, region_seq, vehicle_name, model, vehicle_type_cd, vehicle_num, vehicle_reg_num, model_year, vehicle_reg_area, owner_name, length, width, ton_grade, max_loading_capacity, fuel_type_cd, fuel_efficiency, vehicle_use_type_cd, garage_name, usage_yn, created_at, creator_seq, modified_at, modifier_seq) VALUES ((SELECT center_seq FROM t_center WHERE center_name='롯데택배 판교동원대리점'), NULL, (SELECT region_seq FROM t_region WHERE region_name='분당 수내동권역'), '판교 06호차', '마이티', 'WING_BODY', '12가 3406', '서울18바3406', '2022', '경기', '김오비고', '5.2m', '2.1m', '1톤', '1000kg', 'GASOLINE', '8.5km/L', 'OWN', '판교차고지', 'Y', NOW(), 1, NOW(), 1);
INSERT INTO public.t_vehicle (center_seq, driver_seq, region_seq, vehicle_name, model, vehicle_type_cd, vehicle_num, vehicle_reg_num, model_year, vehicle_reg_area, owner_name, length, width, ton_grade, max_loading_capacity, fuel_type_cd, fuel_efficiency, vehicle_use_type_cd, garage_name, usage_yn, created_at, creator_seq, modified_at, modifier_seq) VALUES ((SELECT center_seq FROM t_center WHERE center_name='판교 롯데마트'), NULL, (SELECT region_seq FROM t_region WHERE region_name='분당 정자동권역'), '판교 07호차', '마이티', 'CARGO', '12가 3407', '서울19바3407', '2023', '경기', '김오비고', '5.2m', '2.1m', '1톤', '1000kg', 'DIESEL', '8.5km/L', 'RENTED', '판교차고지', 'Y', NOW(), 1, NOW(), 1);
INSERT INTO public.t_vehicle (center_seq, driver_seq, region_seq, vehicle_name, model, vehicle_type_cd, vehicle_num, vehicle_reg_num, model_year, vehicle_reg_area, owner_name, length, width, ton_grade, max_loading_capacity, fuel_type_cd, fuel_efficiency, vehicle_use_type_cd, garage_name, usage_yn, created_at, creator_seq, modified_at, modifier_seq) VALUES ((SELECT center_seq FROM t_center WHERE center_name='롯데택배 판교동원대리점'), NULL, (SELECT region_seq FROM t_region WHERE region_name='분당 분당동권역'), '판교 08호차', '마이티', 'BOX_TRUCK', '12가 3408', '서울20바3408', '2020', '경기', '김오비고', '5.2m', '2.1m', '1톤', '1000kg', 'ELECTRIC', '8.5km/L', 'OWN', '판교차고지', 'Y', NOW(), 1, NOW(), 1);
INSERT INTO public.t_vehicle (center_seq, driver_seq, region_seq, vehicle_name, model, vehicle_type_cd, vehicle_num, vehicle_reg_num, model_year, vehicle_reg_area, owner_name, length, width, ton_grade, max_loading_capacity, fuel_type_cd, fuel_efficiency, vehicle_use_type_cd, garage_name, usage_yn, created_at, creator_seq, modified_at, modifier_seq) VALUES ((SELECT center_seq FROM t_center WHERE center_name='판교 롯데마트'), NULL, (SELECT region_seq FROM t_region WHERE region_name='분당 야탑동권역'), '판교 09호차', '마이티', 'WING_BODY', '12가 3409', '서울21바3409', '2021', '경기', '김오비고', '5.2m', '2.1m', '1톤', '1000kg', 'LPG', '8.5km/L', 'RENTED', '판교차고지', 'Y', NOW(), 1, NOW(), 1);
INSERT INTO public.t_vehicle (center_seq, driver_seq, region_seq, vehicle_name, model, vehicle_type_cd, vehicle_num, vehicle_reg_num, model_year, vehicle_reg_area, owner_name, length, width, ton_grade, max_loading_capacity, fuel_type_cd, fuel_efficiency, vehicle_use_type_cd, garage_name, usage_yn, created_at, creator_seq, modified_at, modifier_seq) VALUES ((SELECT center_seq FROM t_center WHERE center_name='롯데택배 판교동원대리점'), NULL, (SELECT region_seq FROM t_region WHERE region_name='분당 이매동권역'), '판교 10호차', '마이티', 'CARGO', '12가 3410', '서울22바3410', '2022', '경기', '김오비고', '5.2m', '2.1m', '1톤', '1000kg', 'GASOLINE', '8.5km/L', 'OWN', '판교차고지', 'Y', NOW(), 1, NOW(), 1);
INSERT INTO public.t_vehicle (center_seq, driver_seq, region_seq, vehicle_name, model, vehicle_type_cd, vehicle_num, vehicle_reg_num, model_year, vehicle_reg_area, owner_name, length, width, ton_grade, max_loading_capacity, fuel_type_cd, fuel_efficiency, vehicle_use_type_cd, garage_name, usage_yn, created_at, creator_seq, modified_at, modifier_seq) VALUES ((SELECT center_seq FROM t_center WHERE center_name='판교 롯데마트'), NULL, (SELECT region_seq FROM t_region WHERE region_name='분당 매송동권역'), '판교 11호차', '마이티', 'BOX_TRUCK', '12가 3411', '서울23바3411', '2023', '경기', '김오비고', '5.2m', '2.1m', '1톤', '1000kg', 'DIESEL', '8.5km/L', 'RENTED', '판교차고지', 'Y', NOW(), 1, NOW(), 1);
INSERT INTO public.t_vehicle (center_seq, driver_seq, region_seq, vehicle_name, model, vehicle_type_cd, vehicle_num, vehicle_reg_num, model_year, vehicle_reg_area, owner_name, length, width, ton_grade, max_loading_capacity, fuel_type_cd, fuel_efficiency, vehicle_use_type_cd, garage_name, usage_yn, created_at, creator_seq, modified_at, modifier_seq) VALUES ((SELECT center_seq FROM t_center WHERE center_name='롯데택배 판교동원대리점'), NULL, (SELECT region_seq FROM t_region WHERE region_name='분당 구미동권역'), '판교 12호차', '마이티', 'WING_BODY', '12가 3412', '서울24바3412', '2020', '경기', '김오비고', '5.2m', '2.1m', '1톤', '1000kg', 'ELECTRIC', '8.5km/L', 'OWN', '판교차고지', 'Y', NOW(), 1, NOW(), 1);
INSERT INTO public.t_vehicle (center_seq, driver_seq, region_seq, vehicle_name, model, vehicle_type_cd, vehicle_num, vehicle_reg_num, model_year, vehicle_reg_area, owner_name, length, width, ton_grade, max_loading_capacity, fuel_type_cd, fuel_efficiency, vehicle_use_type_cd, garage_name, usage_yn, created_at, creator_seq, modified_at, modifier_seq) VALUES ((SELECT center_seq FROM t_center WHERE center_name='판교 롯데마트'), NULL, (SELECT region_seq FROM t_region WHERE region_name='분당 금곡동권역'), '판교 13호차', '마이티', 'CARGO', '12가 3413', '서울25바3413', '2021', '경기', '김오비고', '5.2m', '2.1m', '1톤', '1000kg', 'LPG', '8.5km/L', 'RENTED', '판교차고지', 'Y', NOW(), 1, NOW(), 1);
INSERT INTO public.t_vehicle (center_seq, driver_seq, region_seq, vehicle_name, model, vehicle_type_cd, vehicle_num, vehicle_reg_num, model_year, vehicle_reg_area, owner_name, length, width, ton_grade, max_loading_capacity, fuel_type_cd, fuel_efficiency, vehicle_use_type_cd, garage_name, usage_yn, created_at, creator_seq, modified_at, modifier_seq) VALUES ((SELECT center_seq FROM t_center WHERE center_name='롯데택배 판교동원대리점'), NULL, (SELECT region_seq FROM t_region WHERE region_name='분당 대장동권역'), '판교 14호차', '마이티', 'BOX_TRUCK', '12가 3414', '서울26바3414', '2022', '경기', '김오비고', '5.2m', '2.1m', '1톤', '1000kg', 'GASOLINE', '8.5km/L', 'OWN', '판교차고지', 'Y', NOW(), 1, NOW(), 1);
INSERT INTO public.t_vehicle (center_seq, driver_seq, region_seq, vehicle_name, model, vehicle_type_cd, vehicle_num, vehicle_reg_num, model_year, vehicle_reg_area, owner_name, length, width, ton_grade, max_loading_capacity, fuel_type_cd, fuel_efficiency, vehicle_use_type_cd, garage_name, usage_yn, created_at, creator_seq, modified_at, modifier_seq) VALUES ((SELECT center_seq FROM t_center WHERE center_name='판교 롯데마트'), NULL, (SELECT region_seq FROM t_region WHERE region_name='분당 석운동권역'), '판교 15호차', '마이티', 'WING_BODY', '12가 3415', '서울27바3415', '2023', '경기', '김오비고', '5.2m', '2.1m', '1톤', '1000kg', 'DIESEL', '8.5km/L', 'RENTED', '판교차고지', 'Y', NOW(), 1, NOW(), 1);
INSERT INTO public.t_vehicle (center_seq, driver_seq, region_seq, vehicle_name, model, vehicle_type_cd, vehicle_num, vehicle_reg_num, model_year, vehicle_reg_area, owner_name, length, width, ton_grade, max_loading_capacity, fuel_type_cd, fuel_efficiency, vehicle_use_type_cd, garage_name, usage_yn, created_at, creator_seq, modified_at, modifier_seq) VALUES ((SELECT center_seq FROM t_center WHERE center_name='롯데택배 판교동원대리점'), NULL, (SELECT region_seq FROM t_region WHERE region_name='분당 하산운동권역'), '판교 16호차', '마이티', 'CARGO', '12가 3416', '서울28바3416', '2020', '경기', '김오비고', '5.2m', '2.1m', '1톤', '1000kg', 'ELECTRIC', '8.5km/L', 'OWN', '판교차고지', 'Y', NOW(), 1, NOW(), 1);
INSERT INTO public.t_vehicle (center_seq, driver_seq, region_seq, vehicle_name, model, vehicle_type_cd, vehicle_num, vehicle_reg_num, model_year, vehicle_reg_area, owner_name, length, width, ton_grade, max_loading_capacity, fuel_type_cd, fuel_efficiency, vehicle_use_type_cd, garage_name, usage_yn, created_at, creator_seq, modified_at, modifier_seq) VALUES ((SELECT center_seq FROM t_center WHERE center_name='판교 롯데마트'), NULL, (SELECT region_seq FROM t_region WHERE region_name='분당 율동권역'), '판교 17호차', '마이티', 'BOX_TRUCK', '12가 3417', '서울29바3417', '2021', '경기', '김오비고', '5.2m', '2.1m', '1톤', '1000kg', 'LPG', '8.5km/L', 'RENTED', '판교차고지', 'Y', NOW(), 1, NOW(), 1);
INSERT INTO public.t_vehicle (center_seq, driver_seq, region_seq, vehicle_name, model, vehicle_type_cd, vehicle_num, vehicle_reg_num, model_year, vehicle_reg_area, owner_name, length, width, ton_grade, max_loading_capacity, fuel_type_cd, fuel_efficiency, vehicle_use_type_cd, garage_name, usage_yn, created_at, creator_seq, modified_at, modifier_seq) VALUES ((SELECT center_seq FROM t_center WHERE center_name='롯데택배 판교동원대리점'), NULL, (SELECT region_seq FROM t_region WHERE region_name='분당 궁내동권역'), '판교 18호차', '마이티', 'WING_BODY', '12가 3418', '서울30바3418', '2022', '경기', '김오비고', '5.2m', '2.1m', '1톤', '1000kg', 'GASOLINE', '8.5km/L', 'OWN', '판교차고지', 'Y', NOW(), 1, NOW(), 1);
INSERT INTO public.t_vehicle (center_seq, driver_seq, region_seq, vehicle_name, model, vehicle_type_cd, vehicle_num, vehicle_reg_num, model_year, vehicle_reg_area, owner_name, length, width, ton_grade, max_loading_capacity, fuel_type_cd, fuel_efficiency, vehicle_use_type_cd, garage_name, usage_yn, created_at, creator_seq, modified_at, modifier_seq) VALUES ((SELECT center_seq FROM t_center WHERE center_name='판교 롯데마트'), NULL, (SELECT region_seq FROM t_region WHERE region_name='분당 동원동권역'), '판교 19호차', '마이티', 'CARGO', '12가 3419', '서울31바3419', '2023', '경기', '김오비고', '5.2m', '2.1m', '1톤', '1000kg', 'DIESEL', '8.5km/L', 'RENTED', '판교차고지', 'Y', NOW(), 1, NOW(), 1);
INSERT INTO public.t_vehicle (center_seq, driver_seq, region_seq, vehicle_name, model, vehicle_type_cd, vehicle_num, vehicle_reg_num, model_year, vehicle_reg_area, owner_name, length, width, ton_grade, max_loading_capacity, fuel_type_cd, fuel_efficiency, vehicle_use_type_cd, garage_name, usage_yn, created_at, creator_seq, modified_at, modifier_seq) VALUES ((SELECT center_seq FROM t_center WHERE center_name='롯데택배 판교동원대리점'), NULL, (SELECT region_seq FROM t_region WHERE region_name='분당 여수동권역'), '판교 20호차', '마이티', 'BOX_TRUCK', '12가 3420', '서울32바3420', '2020', '경기', '김오비고', '5.2m', '2.1m', '1톤', '1000kg', 'ELECTRIC', '8.5km/L', 'OWN', '판교차고지', 'Y', NOW(), 1, NOW(), 1);
